### ISSUE TITLE
Max query memory per node cannot be greater than the max query total memory per node.

### ISSUE THREAD

**Issue by voycey** [smizy/docker-presto#2]
I am trying to run this as a quick setup and I am receiving the following:

```17) Error injecting constructor, java.lang.IllegalArgumentException: Max query memory per node cannot be greater than the max query total memory per node.
  at com.facebook.presto.memory.LocalMemoryManager.<init>(LocalMemoryManager.java:46)
  at com.facebook.presto.server.ServerMainModule.setup(ServerMainModule.java:327)
  while locating com.facebook.presto.memory.LocalMemoryManager
    for the 6th parameter of com.facebook.presto.execution.SqlTaskManager.<init>(SqlTaskManager.java:121)
  at com.facebook.presto.server.ServerMainModule.setup(ServerMainModule.java:314)
  while locating com.facebook.presto.execution.SqlTaskManager
  while locating com.facebook.presto.execution.TaskManager
    for the 1st parameter of com.facebook.presto.server.GracefulShutdownHandler.<init>(GracefulShutdownHandler.java:65)
  at com.facebook.presto.server.GracefulShutdownModule.setup(GracefulShutdownModule.java:27)
  while locating com.facebook.presto.server.GracefulShutdownHandler
    for the 5th parameter of com.facebook.presto.server.ServerInfoResource.<init>(ServerInfoResource.java:55)
  at com.facebook.presto.server.ServerMainModule.setup(ServerMainModule.java:466)
  while locating com.facebook.presto.server.ServerInfoResource
Caused by: java.lang.IllegalArgumentException: Max query memory per node cannot be greater than the max query total memory per node.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:135)
	at com.facebook.presto.memory.LocalMemoryManager.configureMemoryPools(LocalMemoryManager.java:61)
	at com.facebook.presto.memory.LocalMemoryManager.<init>(LocalMemoryManager.java:53)
	at com.facebook.presto.memory.LocalMemoryManager$$FastClassByGuice$$80707266.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:148)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:148)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:148)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:148)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:241)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:115)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)
```

I've tried various settings in the docker compose file but none of them seem to have an effect?

I'm not running this through docker machine if that makes a difference?

**Comment by voycey** [comment]
Commenting out the defaults in the docker-compose file sorts this out temporary but I don't know whether the defaults are sane?
